import 'dart:ui';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../data/datasources/local_storage.dart';
import 'providers.dart';

enum AppLanguage { tr, en, de, es, pt, zh }

class LanguageNotifier extends Notifier<AppLanguage> {
  late final LocalStorage _storage;

  @override
  AppLanguage build() {
    _storage = ref.watch(localStorageProvider);
    final savedCode = _storage.getLanguage();
    
    if (savedCode != null) {
      return AppLanguage.values.firstWhere(
        (l) => l.name == savedCode,
        orElse: () => AppLanguage.tr,
      );
    }
    
    // Fallback to system locale
    final systemLocale = PlatformDispatcher.instance.locale.languageCode;
    return AppLanguage.values.firstWhere(
      (l) => l.name == systemLocale,
      orElse: () => AppLanguage.tr,
    );
  }

  Future<void> setLanguage(AppLanguage language) async {
    state = language;
    await _storage.saveLanguage(language.name);
  }

  String translate(String key) {
    final languageCode = state.name;
    final dict = _translations[key];
    if (dict == null) return key;
    return dict[languageCode] ?? dict['en'] ?? key;
  }
}

final languageProvider = NotifierProvider<LanguageNotifier, AppLanguage>(() {
  return LanguageNotifier();
});

// Translation Dictionary for TR, EN, DE, ES, PT, ZH
const Map<String, Map<String, String>> _translations = {
  // Splash Screen
  'splash_welcome': {
    'tr': 'Hoş Geldiniz',
    'en': 'Welcome',
    'de': 'Willkommen',
    'es': 'Bienvenido',
    'pt': 'Bem-vindo',
    'zh': '欢迎',
  },
  'splash_subtitle': {
    'tr': 'Kişisel Medya Merkeziniz',
    'en': 'Your Personal Media Hub',
    'de': 'Ihr persönliches Medienzentrum',
    'es': 'Su centro de medios personal',
    'pt': 'Seu hub de mídia pessoal',
    'zh': '您的个人媒体中心',
  },
  'splash_connecting': {
    'tr': 'Sunucuya bağlanılıyor...',
    'en': 'Connecting to server...',
    'de': 'Verbindung zum Server wird hergestellt...',
    'es': 'Conectando al servidor...',
    'pt': 'Conectando ao servidor...',
    'zh': '正在连接服务器...',
  },
  'splash_logging_in': {
    'tr': 'Giriş yapılıyor...',
    'en': 'Logging in...',
    'de': 'Einloggen...',
    'es': 'Iniciando sesión...',
    'pt': 'Fazendo login...',
    'zh': '正在登录...',
  },

  // Login Screen
  'login_title': {
    'tr': 'IPTV Servisinize Bağlanın',
    'en': 'Connect to your IPTV Service',
    'de': 'Verbinden Sie Ihren IPTV-Dienst',
    'es': 'Conecte a su servicio IPTV',
    'pt': 'Conecte-se ao seu serviço de IPTV',
    'zh': '连接到您的 IPTV 服务',
  },
  'login_server_url': {
    'tr': 'Sunucu URL',
    'en': 'Server URL',
    'de': 'Server-URL',
    'es': 'URL del Servidor',
    'pt': 'URL do Servidor',
    'zh': '服务器 URL',
  },
  'login_username': {
    'tr': 'Kullanıcı Adı',
    'en': 'Username',
    'de': 'Benutzername',
    'es': 'Nombre de usuario',
    'pt': 'Nome de usuário',
    'zh': '用户名',
  },
  'login_password': {
    'tr': 'Şifre',
    'en': 'Password',
    'de': 'Passwort',
    'es': 'Contraseña',
    'pt': 'Senha',
    'zh': '密码',
  },
  'login_err_server': {
    'tr': 'Lütfen sunucu adresini girin',
    'en': 'Please enter server URL',
    'de': 'Bitte geben Sie die Server-URL ein',
    'es': 'Por favor ingrese la URL del servidor',
    'pt': 'Por favor, insira a URL do servidor',
    'zh': '请输入服务器 URL',
  },
  'login_err_username': {
    'tr': 'Lütfen kullanıcı adını girin',
    'en': 'Please enter username',
    'de': 'Bitte geben Sie den Benutzernamen ein',
    'es': 'Por favor ingrese el nombre de usuario',
    'pt': 'Por favor, insira o nome de usuário',
    'zh': '请输入用户名',
  },
  'login_err_password': {
    'tr': 'Lütfen şifrenizi girin',
    'en': 'Please enter password',
    'de': 'Bitte geben Sie das Passwort ein',
    'es': 'Por favor ingrese la contraseña',
    'pt': 'Por favor, insira a senha',
    'zh': '请输入密码',
  },
  'last_updated_never': {
    'tr': 'Hiç güncellenmedi',
    'en': 'Never updated',
    'de': 'Nie aktualisiert',
    'es': 'Nunca actualizado',
    'pt': 'Nunca atualizado',
    'zh': '从未更新',
  },
  'last_updated_just_now': {
    'tr': 'Az önce',
    'en': 'Just now',
    'de': 'Gerade eben',
    'es': 'Justo ahora',
    'pt': 'Agora mesmo',
    'zh': '刚刚',
  },
  'last_updated_mins_ago': {
    'tr': 'dk. önce',
    'en': 'mins ago',
    'de': 'Min. her',
    'es': 'min atrás',
    'pt': 'min atrás',
    'zh': '分钟前',
  },
  'last_updated_hours_ago': {
    'tr': 'saat önce',
    'en': 'hours ago',
    'de': 'Stunden her',
    'es': 'horas atrás',
    'pt': 'horas atrás',
    'zh': '小时前',
  },
  'last_updated_days_ago': {
    'tr': 'gün önce',
    'en': 'days ago',
    'de': 'Tagen',
    'es': 'días atrás',
    'pt': 'dias atrás',
    'zh': '天前',
  },
  'last_updated_prefix': {
    'tr': 'Son Güncelleme: ',
    'en': 'Last Updated: ',
    'de': 'Letztes Update: ',
    'es': 'Última actualización: ',
    'pt': 'Última atualização: ',
    'zh': '最后更新: ',
  },
  'search_coming_soon': {
    'tr': 'Yapay Zeka ile Arama Çok Yakında! 🤖',
    'en': 'AI Search Coming Soon! 🤖',
    'de': 'KI-Suche kommt bald! 🤖',
    'es': '¡Búsqueda con IA próximamente! 🤖',
    'pt': 'Pesquisa com IA em breve! 🤖',
    'zh': 'AI 搜索即将推出！🤖',
  },
  'login_submit': {
    'tr': 'Giriş Yap',
    'en': 'Log In',
    'de': 'Einloggen',
    'es': 'Iniciar sesión',
    'pt': 'Entrar',
    'zh': '登录',
  },
  'login_failed_title': {
    'tr': 'Giriş Başarısız',
    'en': 'Login Failed',
    'de': 'Login fehlgeschlagen',
    'es': 'Inicio de sesión fallido',
    'pt': 'Falha no login',
    'zh': '登录失败',
  },
  'login_failed_msg': {
    'tr': 'Lütfen bilgilerinizi kontrol edin',
    'en': 'Please check your credentials',
    'de': 'Bitte überprüfen Sie Ihre Zugangsdaten',
    'es': 'Por favor verifique sus credenciales',
    'pt': 'Por favor, verifique suas credenciais',
    'zh': '请检查您的凭据',
  },
  'login_error': {
    'tr': 'Hata',
    'en': 'Error',
    'de': 'Fehler',
    'es': 'Error',
    'pt': 'Erro',
    'zh': '错误',
  },

  // Dashboard
  'dashboard_welcome': {
    'tr': 'Hoş Geldiniz 👋',
    'en': 'Welcome 👋',
    'de': 'Willkommen 👋',
    'es': 'Bienvenido 👋',
    'pt': 'Bem-vindo 👋',
    'zh': '欢迎 👋',
  },
  'dashboard_recently_watched': {
    'tr': 'Son İzlenenler',
    'en': 'Recently Watched',
    'de': 'Kürzlich angesehen',
    'es': 'Visto recientemente',
    'pt': 'Assistido recentemente',
    'zh': '最近播放',
  },
  'dashboard_favorites': {
    'tr': 'Favorilerim',
    'en': 'My Favorites',
    'de': 'Meine Favoriten',
    'es': 'Mis Favoritos',
    'pt': 'Meus Favoritos',
    'zh': '我的收藏',
  },
  'dashboard_see_all': {
    'tr': 'Tümünü Gör',
    'en': 'See All',
    'de': 'Alle ansehen',
    'es': 'Ver todo',
    'pt': 'Ver todos',
    'zh': '查看全部',
  },
  'dashboard_live': {
    'tr': 'Canlı TV',
    'en': 'Live TV',
    'de': 'Live-TV',
    'es': 'TV en vivo',
    'pt': 'TV ao vivo',
    'zh': '电视直播',
  },
  'dashboard_movies': {
    'tr': 'Filmler',
    'en': 'Movies',
    'de': 'Filme',
    'es': 'Películas',
    'pt': 'Filmes',
    'zh': '电影',
  },
  'dashboard_series': {
    'tr': 'Diziler',
    'en': 'TV Series',
    'de': 'Serien',
    'es': 'Series de TV',
    'pt': 'Séries de TV',
    'zh': '电视剧',
  },
  'dashboard_active': {
    'tr': 'Aktif',
    'en': 'Active',
    'de': 'Aktiv',
    'es': 'Activo',
    'pt': 'Ativo',
    'zh': '活跃/在线',
  },
  'dashboard_no_favorites': {
    'tr': 'Henüz Favori Eklenmedi',
    'en': 'No Favorites Added Yet',
    'de': 'Noch keine Favoriten hinzugefügt',
    'es': 'Aún no se han añadido favoritos',
    'pt': 'Nenhum favorito adicionado ainda',
    'zh': '暂无收藏',
  },
  'dashboard_no_favorites_desc': {
    'tr': 'İçeriği izlerken yıldız simgesine dokunarak hızlıca favorilerinize ekleyebilirsiniz.',
    'en': 'You can quickly add content to your favorites by tapping the star icon while watching.',
    'de': 'Sie können Inhalte schnell zu Ihren Favoriten hinzufügen, indem Sie während des Ansehens auf das Sternsymbol tippen.',
    'es': 'Puede añadir contenido a sus favoritos tocando el icono de estrella mientras lo ve.',
    'pt': 'Você pode adicionar conteúdo aos seus favoritos tocando no ícone de estrela enquanto assiste.',
    'zh': '您可以在观看时点击星形图标，快速将内容添加到收藏夹中。',
  },
  'dashboard_featured_movie': {
    'tr': 'ÖNE ÇIKAN FİLM',
    'en': 'FEATURED MOVIE',
    'de': 'HIGHLIGHT-FILM',
    'es': 'PELÍCULA DESTACADA',
    'pt': 'FILME EM DESTAQUE',
    'zh': '推荐电影',
  },
  'dashboard_featured_series': {
    'tr': 'ÖNE ÇIKAN DİZİ',
    'en': 'FEATURED TV SERIES',
    'de': 'HIGHLIGHT-SERIE',
    'es': 'SERIE DESTACADA',
    'pt': 'SÉRIE EM DESTAQUE',
    'zh': '推荐电视剧',
  },
  'dashboard_live_ch_empty': {
    'tr': 'Canlı TV kanalı',
    'en': 'Live TV channel',
    'de': 'Live-TV-Kanal',
    'es': 'Canal de TV en vivo',
    'pt': 'Canal de TV ao vivo',
    'zh': '电视直播频道',
  },
  'dashboard_movie_empty': {
    'tr': 'film',
    'en': 'movie',
    'de': 'Film',
    'es': 'película',
    'pt': 'filme',
    'zh': '电影',
  },
  'dashboard_series_empty': {
    'tr': 'dizi',
    'en': 'series',
    'de': 'Serie',
    'es': 'serie',
    'pt': 'série',
    'zh': '电视剧',
  },

  // Service Info Modal
  'info_title': {
    'tr': 'Sunucu & Abonelik Bilgisi',
    'en': 'Server & Subscription Info',
    'de': 'Server & Abonnementsinfo',
    'es': 'Información de servidor y suscripción',
    'pt': 'Informações de Servidor e Assinatura',
    'zh': '服务器和订阅信息',
  },
  'info_sub_details': {
    'tr': 'Abonelik Detayları',
    'en': 'Subscription Details',
    'de': 'Abonnement-Details',
    'es': 'Detalles de la suscripción',
    'pt': 'Detalhes da Assinatura',
    'zh': '订阅详情',
  },
  'info_status': {
    'tr': 'Durum',
    'en': 'Status',
    'de': 'Status',
    'es': 'Estado',
    'pt': 'Status',
    'zh': '状态',
  },
  'info_exp_date': {
    'tr': 'Bitiş Tarihi',
    'en': 'Expiration Date',
    'de': 'Ablaufdatum',
    'es': 'Fecha de vencimiento',
    'pt': 'Data de Expiração',
    'zh': '到期时间',
  },
  'info_active_connections': {
    'tr': 'Aktif Bağlantılar',
    'en': 'Active Connections',
    'de': 'Aktive Verbindungen',
    'es': 'Conexiones activas',
    'pt': 'Conexões Ativas',
    'zh': '活跃连接',
  },
  'info_account_type': {
    'tr': 'Hesap Tipi',
    'en': 'Account Type',
    'de': 'Kontotyp',
    'es': 'Tipo de cuenta',
    'pt': 'Tipo de Conta',
    'zh': '账户类型',
  },
  'info_trial': {
    'tr': 'Deneme Hesabı 🧪',
    'en': 'Trial Account 🧪',
    'de': 'Testkonto 🧪',
    'es': 'Cuenta de prueba 🧪',
    'pt': 'Conta de Teste 🧪',
    'zh': '测试账户 🧪',
  },
  'info_unlimited': {
    'tr': 'Sınırsız ♾️',
    'en': 'Unlimited ♾️',
    'de': 'Unbegrenzt ♾️',
    'es': 'Ilimitado ♾️',
    'pt': 'Ilimitado ♾️',
    'zh': '无限制 ♾️',
  },
  'info_server_details': {
    'tr': 'Sunucu Detayları',
    'en': 'Server Details',
    'de': 'Server-Details',
    'es': 'Detalles del servidor',
    'pt': 'Detalhes do Servidor',
    'zh': '服务器详情',
  },
  'info_server_url': {
    'tr': 'Sunucu Adresi',
    'en': 'Server Address',
    'de': 'Serveradresse',
    'es': 'Dirección del servidor',
    'pt': 'Endereço do Servidor',
    'zh': '服务器地址',
  },
  'info_timezone': {
    'tr': 'Saat Dilimi',
    'en': 'Timezone',
    'de': 'Zeitzone',
    'es': 'Zona horaria',
    'pt': 'Fuso Horário',
    'zh': '时区',
  },
  'info_server_time': {
    'tr': 'Sunucu Saati',
    'en': 'Server Time',
    'de': 'Serverzeit',
    'es': 'Hora del servidor',
    'pt': 'Hora do Servidor',
    'zh': '服务器时间',
  },
  'info_allowed_formats': {
    'tr': 'İzin Verilen Formatlar',
    'en': 'Allowed Formats',
    'de': 'Erlaubte Formate',
    'es': 'Formatos permitidos',
    'pt': 'Formatos Permitidos',
    'zh': '允许的格式',
  },
  'info_content_stats': {
    'tr': 'İçerik İstatistikleri',
    'en': 'Content Stats',
    'de': 'Inhaltsstatistiken',
    'es': 'Estadísticas de contenido',
    'pt': 'Estatísticas de Conteúdo',
    'zh': '内容统计',
  },
  'info_live_channels': {
    'tr': 'Canlı TV Kanalları',
    'en': 'Live TV Channels',
    'de': 'Live-TV-Kanäle',
    'es': 'Canales de TV en vivo',
    'pt': 'Canais de TV ao vivo',
    'zh': '电视直播频道',
  },
  'info_movies': {
    'tr': 'Filmler (VOD)',
    'en': 'Movies (VOD)',
    'de': 'Filme (VOD)',
    'es': 'Películas (VOD)',
    'pt': 'Filmes (VOD)',
    'zh': '电影 (VOD)',
  },
  'info_series': {
    'tr': 'Diziler',
    'en': 'TV Series',
    'de': 'Serien',
    'es': 'Series de TV',
    'pt': 'Séries de TV',
    'zh': '电视剧',
  },

  // Settings
  'settings_title': {
    'tr': 'Ayarlar',
    'en': 'Settings',
    'de': 'Einstellungen',
    'es': 'Ajustes',
    'pt': 'Configurações',
    'zh': '设置',
  },
  'settings_account_info': {
    'tr': 'Hesap Bilgileri',
    'en': 'Account Info',
    'de': 'Kontoinformationen',
    'es': 'Información de la cuenta',
    'pt': 'Informações da Conta',
    'zh': '账户信息',
  },
  'settings_server': {
    'tr': 'Sunucu',
    'en': 'Server',
    'de': 'Server',
    'es': 'Servidor',
    'pt': 'Servidor',
    'zh': '服务器',
  },
  'settings_username': {
    'tr': 'Kullanıcı Adı',
    'en': 'Username',
    'de': 'Benutzername',
    'es': 'Nombre de usuario',
    'pt': 'Nome de usuário',
    'zh': '用户名',
  },
  'settings_language': {
    'tr': 'Dil Ayarı',
    'en': 'Language',
    'de': 'Sprache',
    'es': 'Idioma',
    'pt': 'Idioma',
    'zh': '语言设置',
  },
  'settings_logout': {
    'tr': 'Hesaptan Çıkış Yap',
    'en': 'Log Out of Account',
    'de': 'Abmelden vom Konto',
    'es': 'Cerrar sesión de la cuenta',
    'pt': 'Sair da Conta',
    'zh': '退出登录',
  },
  'settings_logout_confirm_title': {
    'tr': 'Çıkış Yap',
    'en': 'Log Out',
    'de': 'Abmelden',
    'es': 'Cerrar sesión',
    'pt': 'Sair',
    'zh': '退出登录',
  },
  'settings_logout_confirm_msg': {
    'tr': 'Hesabınızdan çıkış yapmak istediğinize emin misiniz?',
    'en': 'Are you sure you want to log out of your account?',
    'de': 'Sind Sie sicher, dass Sie sich von Ihrem Konto abmelden möchten?',
    'es': '¿Está seguro de que desea cerrar sesión en su cuenta?',
    'pt': 'Tem certeza de que deseja sair da sua conta?',
    'zh': '您确定要退出登录吗？',
  },
  'settings_cancel': {
    'tr': 'İptal',
    'en': 'Cancel',
    'de': 'Abbrechen',
    'es': 'Cancelar',
    'pt': 'Cancelar',
    'zh': '取消',
  },
  'settings_logout_action': {
    'tr': 'Çıkış',
    'en': 'Logout',
    'de': 'Abmelden',
    'es': 'Salir',
    'pt': 'Sair',
    'zh': '退出',
  },

  // Media Lists
  'media_live_title': {
    'tr': 'Canlı TV',
    'en': 'Live TV',
    'de': 'Live-TV',
    'es': 'TV en vivo',
    'pt': 'TV ao vivo',
    'zh': '电视直播',
  },
  'media_movie_title': {
    'tr': 'Sinema (VOD)',
    'en': 'Cinema (VOD)',
    'de': 'Kino (VOD)',
    'es': 'Cine (VOD)',
    'pt': 'Cinema (VOD)',
    'zh': '影院 (VOD)',
  },
  'media_series_title': {
    'tr': 'Diziler',
    'en': 'TV Series',
    'de': 'Serien',
    'es': 'Series de TV',
    'pt': 'Séries de TV',
    'zh': '电视剧',
  },
  'search_hint': {
    'tr': 'Ara...',
    'en': 'Search...',
    'de': 'Suchen...',
    'es': 'Buscar...',
    'pt': 'Buscar...',
    'zh': '搜索...',
  },
  'category_all': {
    'tr': 'Tümü',
    'en': 'All',
    'de': 'Alle',
    'es': 'Todo',
    'pt': 'Todos',
    'zh': '全部',
  },
  'category_title': {
    'tr': 'Kategoriler',
    'en': 'Categories',
    'de': 'Kategorien',
    'es': 'Categorías',
    'pt': 'Categorias',
    'zh': '分类',
  },
  'media_not_found': {
    'tr': 'İçerik Bulunamadı',
    'en': 'Content Not Found',
    'de': 'Inhalt nicht gefunden',
    'es': 'Contenido no encontrado',
    'pt': 'Conteúdo não encontrado',
    'zh': '未找到内容',
  },
  'media_not_found_desc': {
    'tr': 'Farklı bir arama yapmayı deneyin',
    'en': 'Try making a different search',
    'de': 'Versuchen Sie eine andere Suche',
    'es': 'Intente hacer otra búsqueda',
    'pt': 'Tente fazer uma busca diferente',
    'zh': '尝试重新搜索',
  },
  'channel_no': {
    'tr': 'Kanal No',
    'en': 'Channel No.',
    'de': 'Kanal-Nr.',
    'es': 'Canal Nro.',
    'pt': 'Canal Nº',
    'zh': '频道号',
  },
  'media_movie_label': {
    'tr': 'Film',
    'en': 'Movie',
    'de': 'Film',
    'es': 'Película',
    'pt': 'Filme',
    'zh': '电影',
  },
  'media_series_label': {
    'tr': 'Dizi',
    'en': 'Series',
    'de': 'Serie',
    'es': 'Serie',
    'pt': 'Série',
    'zh': '电视剧',
  },

  // Series detail sheet
  'series_no_plot': {
    'tr': 'Açıklama bulunmuyor.',
    'en': 'No description available.',
    'de': 'Keine Beschreibung verfügbar.',
    'es': 'No hay descripción disponible.',
    'pt': 'Nenhuma descrição disponível.',
    'zh': '暂无描述。',
  },
  'series_season_label': {
    'tr': 'Sezon',
    'en': 'Season',
    'de': 'Staffel',
    'es': 'Temporada',
    'pt': 'Temporada',
    'zh': '季',
  },
  'series_no_episodes': {
    'tr': 'Bu sezona ait bölüm bulunamadı.',
    'en': 'No episodes found for this season.',
    'de': 'Keine Episoden für diese Staffel gefunden.',
    'es': 'No se encontraron episodios para esta temporada.',
    'pt': 'Nenhum episódio encontrado para esta temporada.',
    'zh': '该季未找到任何剧集。',
  },
  'series_episode_label': {
    'tr': 'Bölüm',
    'en': 'Episode',
    'de': 'Episode',
    'es': 'Episodio',
    'pt': 'Episódio',
    'zh': '集',
  },
  'series_file': {
    'tr': 'Dosya',
    'en': 'File',
    'de': 'Datei',
    'es': 'Archivo',
    'pt': 'Arquivo',
    'zh': '文件',
  },

  // Player controls
  'player_back': {
    'tr': 'Geri',
    'en': 'Back',
    'de': 'Zurück',
    'es': 'Volver',
    'pt': 'Voltar',
    'zh': '返回',
  },
  'player_live_label': {
    'tr': 'Canlı Yayın',
    'en': 'Live',
    'de': 'Live',
    'es': 'En vivo',
    'pt': 'Ao vivo',
    'zh': '直播',
  },
  'player_channel_list': {
    'tr': 'Kanal Listesi',
    'en': 'Channel List',
    'de': 'Kanalliste',
    'es': 'Lista de canales',
    'pt': 'Lista de Canais',
    'zh': '频道列表',
  },
  'player_playlist': {
    'tr': 'Oynatma Listesi',
    'en': 'Playlist',
    'de': 'Wiedergabeliste',
    'es': 'Lista de reproducción',
    'pt': 'Playlist',
    'zh': '播放列表',
  },
  'player_next_program': {
    'tr': 'Sıradaki Program',
    'en': 'Next Program',
    'de': 'Nächstes Programm',
    'es': 'Siguiente programa',
    'pt': 'Próximo programa',
    'zh': '下一个节目',
  },
  'player_epg_guide': {
    'tr': 'Program Akışı',
    'en': 'EPG Guide',
    'de': 'Programmführer',
    'es': 'Guía EPG',
    'pt': 'Guia EPG',
    'zh': '节目指南',
  },
  'player_no_epg': {
    'tr': 'Yayın Akışı Bulunmuyor',
    'en': 'No program guide available',
    'de': 'Kein Programmführer verfügbar',
    'es': 'No hay guía de programas disponible',
    'pt': 'Guia de programação indisponível',
    'zh': '暂无节目指南',
  },
  'player_aspect_ratio': {
    'tr': 'En Boy Oranı',
    'en': 'Aspect Ratio',
    'de': 'Bildformat',
    'es': 'Relación de aspecto',
    'pt': 'Proporção',
    'zh': '画面比例',
  },
  'player_aspect_auto': {
    'tr': 'Otomatik',
    'en': 'Auto',
    'de': 'Auto',
    'es': 'Auto',
    'pt': 'Auto',
    'zh': '自动',
  },
  'player_aspect_fill_cover': {
    'tr': 'Doldur (Cover)',
    'en': 'Fill (Cover)',
    'de': 'Füllen (Cover)',
    'es': 'Rellenar (Cover)',
    'pt': 'Preencher (Cover)',
    'zh': '填充裁剪',
  },
  'player_aspect_stretch_fill': {
    'tr': 'Esnet (Esnet)',
    'en': 'Stretch (Fill)',
    'de': 'Strecken (Ausfüllen)',
    'es': 'Estirar (Llenar)',
    'pt': 'Esticar (Preencher)',
    'zh': '拉伸填充',
  },
  'player_hud_auto': {
    'tr': 'Otomatik',
    'en': 'Auto',
    'de': 'Auto',
    'es': 'Auto',
    'pt': 'Auto',
    'zh': '自动',
  },
  'player_hud_fill': {
    'tr': 'Ekrana Yay (Doldur)',
    'en': 'Zoom to Fill',
    'de': 'Zoom zum Ausfüllen',
    'es': 'Zoom para llenar',
    'pt': 'Zoom para Preencher',
    'zh': '缩放填充',
  },
  'player_hud_stretch': {
    'tr': 'Ekrana Sığdır (Esnet)',
    'en': 'Stretch to Fit',
    'de': 'An Bildanpassung strecken',
    'es': 'Estirar para ajustar',
    'pt': 'Esticar para Ajustar',
    'zh': '拉伸适应',
  },
  'player_hud_widescreen': {
    'tr': 'Geniş Ekran',
    'en': 'Widescreen',
    'de': 'Breitbild',
    'es': 'Pantalla ancha',
    'pt': 'Widescreen',
    'zh': '宽屏',
  },
  'player_hud_standard': {
    'tr': 'Standart',
    'en': 'Standard',
    'de': 'Standard',
    'es': 'Estándar',
    'pt': 'Padrão',
    'zh': '标准',
  },
  'player_hud_cinematic': {
    'tr': 'Sinematik',
    'en': 'Cinematic',
    'de': 'Kinoreif',
    'es': 'Cinemático',
    'pt': 'Cinemático',
    'zh': '电影效果',
  },
  'player_hud_square': {
    'tr': 'Kare',
    'en': 'Square',
    'de': 'Quadratisch',
    'es': 'Cuadrado',
    'pt': 'Quadrado',
    'zh': '方形',
  },
  'info_unknown': {
    'tr': 'Bilinmiyor',
    'en': 'Unknown',
    'de': 'Unbekannt',
    'es': 'Desconocido',
    'pt': 'Desconhecido',
    'zh': '未知',
  },
  'player_error': {
    'tr': 'Yayın yüklenirken hata oluştu',
    'en': 'An error occurred while loading the stream',
    'de': 'Beim Laden des Streams ist ein Fehler aufgetreten',
    'es': 'Ocurrió un error al cargar la transmisión',
    'pt': 'Ocorreu um erro ao carregar a transmissão',
    'zh': '加载流时出错',
  },
  'player_loading': {
    'tr': 'Yayın Yükleniyor...',
    'en': 'Loading Stream...',
    'de': 'Stream wird geladen...',
    'es': 'Cargando transmisión...',
    'pt': 'Carregando transmissão...',
    'zh': '正在加载流...',
  },
  'player_volume': {
    'tr': 'Ses',
    'en': 'Volume',
    'de': 'Lautstärke',
    'es': 'Volumen',
    'pt': 'Volume',
    'zh': '音量',
  },
  'player_brightness': {
    'tr': 'Parlaklık',
    'en': 'Brightness',
    'de': 'Helligkeit',
    'es': 'Brillo',
    'pt': 'Brilho',
    'zh': '亮度',
  },
  'player_now': {
    'tr': 'Şimdi',
    'en': 'Now',
    'de': 'Jetzt',
    'es': 'Ahora',
    'pt': 'Agora',
    'zh': '正在播放',
  },
  'player_quick_zap': {
    'tr': 'Hızlı Geçiş',
    'en': 'Quick Zap',
    'de': 'Schnellzappen',
    'es': 'Zap rápido',
    'pt': 'Zap rápido',
    'zh': '快速切台',
  },
  'tab_dashboard': {
    'tr': 'Panel',
    'en': 'Dashboard',
    'de': 'Dashboard',
    'es': 'Panel',
    'pt': 'Painel',
    'zh': '仪表盘',
  },
  'tab_live': {
    'tr': 'Canlı',
    'en': 'Live',
    'de': 'Live',
    'es': 'Vivo',
    'pt': 'Ao Vivo',
    'zh': '直播',
  },
  'tab_movies': {
    'tr': 'Film',
    'en': 'Movie',
    'de': 'Film',
    'es': 'Cine',
    'pt': 'Filme',
    'zh': '电影',
  },
  'tab_series': {
    'tr': 'Dizi',
    'en': 'Series',
    'de': 'Serie',
    'es': 'Serie',
    'pt': 'Série',
    'zh': '电视剧',
  },
  'tab_favorites': {
    'tr': 'Favoriler',
    'en': 'Favorites',
    'de': 'Favoriten',
    'es': 'Favoritos',
    'pt': 'Favoritos',
    'zh': '收藏',
  },
  'tab_settings': {
    'tr': 'Ayarlar',
    'en': 'Settings',
    'de': 'Einstellungen',
    'es': 'Ajustes',
    'pt': 'Config.',
    'zh': '设置',
  },
  'live_alternatives': {
    'tr': 'Alternatif',
    'en': 'Alternatives',
    'de': 'Alternativen',
    'es': 'Alternativas',
    'pt': 'Alternativas',
    'zh': '备用源',
  },
  'update_all': {
    'tr': 'Tümünü Güncelle',
    'en': 'Update All',
    'de': 'Alles aktualisieren',
    'es': 'Actualizar todo',
    'pt': 'Atualizar tudo',
    'zh': '更新全部',
  },
  'updating': {
    'tr': 'Tüm İçerik Güncelleniyor...',
    'en': 'Updating All Content...',
    'de': 'Aktualisiere alle Inhalte...',
    'es': 'Actualizando todo el contenido...',
    'pt': 'Atualizando todo o conteúdo...',
    'zh': '正在更新所有内容...',
  },
  'update_success': {
    'tr': 'İçerik başarıyla güncellendi!',
    'en': 'Content updated successfully!',
    'de': 'Inhalt erfolgreich aktualisiert!',
    'es': '¡Contenido actualizado con éxito!',
    'pt': 'Conteúdo atualizado com sucesso!',
    'zh': '内容已成功更新！',
  },
  'update_error': {
    'tr': 'Güncelleme sırasında hata oluştu!',
    'en': 'An error occurred during update!',
    'de': 'Fehler beim Aktualisieren!',
    'es': '¡Ocurrió un error al actualizar!',
    'pt': 'Ocorreu um erro ao atualizar!',
    'zh': '更新时出错！',
  },
  'home_sports_center': {
    'tr': 'SPOR MERKEZİ',
    'en': 'SPORTS CENTER',
    'de': 'SPORTZENTRUM',
    'es': 'CENTRO DEPORTIVO',
    'pt': 'CENTRO ESPORTIVO',
    'zh': '体育中心',
  },
  'home_sports_desc': {
    'tr': 'Canlı Maçlar ve Belgeseller',
    'en': 'Live Matches and Documentaries',
    'de': 'Live-Spiele und Dokumentationen',
    'es': 'Partidos en vivo y documentales',
    'pt': 'Partidas ao Vivo e Documentários',
    'zh': '现场比赛和纪录片',
  },
  'home_horror_room': {
    'tr': 'KORKU ODASI',
    'en': 'HORROR ROOM',
    'de': 'HORRORZIMMER',
    'es': 'SALA DE TERROR',
    'pt': 'SALA DE TERROR',
    'zh': '恐怖房间',
  },
  'home_horror_desc': {
    'tr': 'Kanınızı donduracak filmler ve diziler',
    'en': 'Blood-curdling movies and TV series',
    'de': 'Blutrünstige Filme und Fernsehserien',
    'es': 'Películas y series espeluznantes',
    'pt': 'Filmes e séries de gelar o sangue',
    'zh': '令人毛骨悚然的电影和电视剧',
  },
  'horror_movies': {
    'tr': 'Lanetli Filmler',
    'en': 'Cursed Movies',
    'de': 'Verfluchte Filme',
    'es': 'Películas Malditas',
    'pt': 'Filmes Amaldiçoados',
    'zh': '被诅咒的电影',
  },
  'horror_series': {
    'tr': 'Korku Dizileri',
    'en': 'Horror Series',
    'de': 'Horror-Serien',
    'es': 'Series de Terror',
    'pt': 'Séries de Terror',
    'zh': '恐怖系列',
  },
  'horror_not_found_movies': {
    'tr': 'Korku filmi bulunamadı.',
    'en': 'No horror movies found.',
    'de': 'Keine Horrorfilme gefunden.',
    'es': 'No se encontraron películas de terror.',
    'pt': 'Nenhum filme de terror encontrado.',
    'zh': '未找到恐怖电影。',
  },
  'horror_not_found_series': {
    'tr': 'Korku dizisi bulunamadı.',
    'en': 'No horror series found.',
    'de': 'Keine Horror-Serien gefunden.',
    'es': 'No se encontraron series de terror.',
    'pt': 'Nenhuma série de terror encontrada.',
    'zh': '未找到恐怖系列。',
  },
  'sports_vod_movies': {
    'tr': 'Önerilen Spor Filmleri',
    'en': 'Recommended Sports Movies',
    'de': 'Empfohlene Sportfilme',
    'es': 'Películas Deportivas Recomendadas',
    'pt': 'Filmes Esportivos Recomendados',
    'zh': '推荐体育电影',
  },
  'sports_vod_not_found': {
    'tr': 'Spor filmi bulunamadı.',
    'en': 'No sports movies found.',
    'de': 'Keine Sportfilme gefunden.',
    'es': 'No se encontraron películas deportivas.',
    'pt': 'Nenhum filme esportivo encontrado.',
    'zh': '未找到体育电影。',
  },
};

extension RefL10nExtension on WidgetRef {
  String tr(String key) {
    watch(languageProvider); // Reactively listen to language updates to trigger UI rebuilds
    return read(languageProvider.notifier).translate(key);
  }
}

